# Generated by Django 3.0.2 on 2022-07-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(choices=[('seller', 'Vendedor'), ('reseller', 'Revendedor'), ('ADMINISTRATOR', 'Administrador')], max_length=15, verbose_name='profile'),
        ),
    ]
