# Generated by Django 3.0.2 on 2022-07-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220708_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Gerente'), ('ANALYST', 'Analista'), ('ASSISTANT', 'Assistente')], max_length=15, verbose_name='ocupação'),
        ),
    ]
