# Generated by Django 3.0.2 on 2022-07-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220709_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='name',
        ),
    ]
