# Generated by Django 3.0.2 on 2022-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220709_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='name',
            field=models.CharField(default='', max_length=180, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
