# Generated by Django 3.0.2 on 2022-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220710_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ocuppation',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Gerente'), ('ANALYST', 'Analista'), ('ASSISTANT', 'Assistente')], max_length=20, verbose_name='ocupação'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='perfil_name',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrador'), ('CONTROLLER', 'Auditor'), ('VISITOR', 'Visitante'), ('PROVIDER', 'Fornecedor'), ('EMPLOYEE', 'Funcionário')], max_length=20, verbose_name='função'),
        ),
    ]
